export enum BatchStatus {
  CREATED = 'CREATED',
  IN_TRANSIT = 'IN_TRANSIT',
  RECEIVED = 'RECEIVED',
  SOLD = 'SOLD',
  DISCARDED = 'DISCARDED',
  LOST = 'LOST',
  DELAYED = 'DELAYED',
  INVESTIGATING = 'INVESTIGATING',
}
