export enum TimelineEventType {
  CREATED = 'CREATED',
  SHIPPED = 'SHIPPED',
  RECEIVED = 'RECEIVED',
  SOLD = 'SOLD',
  DISCARDED = 'DISCARDED',
  DELAYED = 'DELAYED',
  INVESTIGATING = 'INVESTIGATING',
  LOST = 'LOST',
  DAMAGED = 'DAMAGED',
  CANCELLED = 'CANCELLED',
  INVENTORY_ADJUSTED = 'INVENTORY_ADJUSTED',
  INCIDENT_CLOSED = 'INCIDENT_CLOSED',
}
